/****** Object:  Table [dbo].[tblUOM]    Committed by VersionSQL https://www.versionsql.com ******/

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[tblUOM](
	[UOM_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[UOM_Desc] [nvarchar](50) NULL,
 CONSTRAINT [PK_tblUOM] PRIMARY KEY CLUSTERED 
(
	[UOM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
